name: Publish Package

on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      gpr:
        default: "yes"
        description: Publish to GPR?
        required: true

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare the source code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    if: github.event_name == 'release' || github.event.inputs.gpr == 'yes'
    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Node.js environment
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Create tarball
        run: npm pack

      - name: Save tarball
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: package
          path: "*.tgz"
          retention-days: 1

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      statuses: write
      packages: write
    strategy:
      matrix:
        registry:
          - gpr
        include:
          - registry: gpr
            secret: GITHUB_TOKEN
            registry_url: https://npm.pkg.github.com/
    steps:
      - name: Set commit status to PENDING
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Publish to ${{ matrix.registry }}
          sha: ${{ github.sha }}
        if: github.event.inputs[matrix.registry] == 'yes' || github.event_name == 'release'

      - name: Set up Node.js environment
        if: github.event.inputs[matrix.registry] == 'yes' || github.event_name == 'release'
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          registry-url: ${{ matrix.registry_url }}

      - name: Download tarball
        if: github.event.inputs[matrix.registry] == 'yes' || github.event_name == 'release'
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: package

      - name: Publish package
        if: github.event.inputs[matrix.registry] == 'yes' || github.event_name == 'release'
        run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.secret] }}

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Publish to ${{ matrix.registry }}
          sha: ${{ github.sha }}
        if: always() && (github.event.inputs[matrix.registry] == 'yes' || github.event_name == 'release')
